# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "courses", :force => true do |t|
    t.column "title",          :string,   :limit => 100, :default => "", :null => false
    t.column "description",        :text
    t.column "lecturer_id",    :integer
    t.column "status",         :string,   :limit => 20,  :default => "", :null => false
    t.column "course_limit", :integer,  :limit => 4,   :default => 0,  :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "students_count", :integer,  :limit => 4,   :default => 0,  :null => false
  end

  add_index "courses", ["lecturer_id"], :name => "index_courses_on_lecturer_id"

  create_table "categories", :force => true do |t|
    t.column "name",        :string, :limit => 50, :default => "", :null => false
    t.column "short_name",  :string, :limit => 30, :default => "", :null => false
    t.column "description", :string,               :default => "", :null => false
  end

  create_table "categories_courses", :force => true do |t|
    t.column "category_id", :integer, :null => false
    t.column "course_id",     :integer, :null => false
  end

  add_index "categories_courses", ["category_id"], :name => "index_categories_courses_on_category_id"
  add_index "categories_courses", ["course_id"], :name => "index_categories_courses_on_course_id"

  create_table "students", :force => true do |t|
    t.column "course_id",      :integer,                :default => 0,  :null => false
    t.column "student_name",   :string,   :limit => 25, :default => "", :null => false
    t.column "student_email",  :string,   :limit => 25, :default => "", :null => false
    t.column "tel",            :integer,                :default => 0,  :null => false
    t.column "lecturer_email", :string,   :limit => 50, :default => "", :null => false
    t.column "subjects",      :text,                   :default => "", :null => false
    t.column "status",       :string,   :limit => 25, :default => "", :null => false
    t.column "created_at",   :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "username",        :string,  :limit => 25, :default => "", :null => false
    t.column "hashed_password", :string,  :limit => 40, :default => "", :null => false
    t.column "first_name",      :string,  :limit => 25, :default => "", :null => false
    t.column "last_name",       :string,  :limit => 40, :default => "", :null => false
    t.column "email",           :string,  :limit => 50, :default => "", :null => false
    t.column "display_name",    :string,  :limit => 25, :default => "", :null => false
    t.column "user_level",      :integer, :limit => 3,  :default => 0,  :null => false
    t.column "courses_count",   :integer, :limit => 6,  :default => 0,  :null => false
    t.column "salt",            :string,  :limit => 40
  end

end
